# Generated by Django 4.0.3 on 2022-03-05 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'review', 'verbose_name_plural': 'reviews'},
        ),
        migrations.AlterModelTable(
            name='review',
            table='review',
        ),
    ]
