# Generated by Django 4.0.3 on 2022-03-05 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_review_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'permissions': [('can_look_review_list', 'Может просмотреть страницу со списком отзывов')], 'verbose_name': 'review', 'verbose_name_plural': 'reviews'},
        ),
    ]
